system_prompt = "You are a helpful assistant"

[llamacpp]
base_url = "http://localhost:8080"
api_key = "not-required"
timeout_secs = 1800

[ollama]
base_url = "http://localhost:11434"
api_key = "not-required"
timeout_secs = 1
